# -*- encoding=utf-8
from money import Currency


class CurrencySource(dict):
    def get_default(self):
        return self['XXX']

CURRENCY = CurrencySource()
CURRENCY['XXX'] = Currency(code="XXX", numeric="999")
#
# Definitions of ISO 4217 Currencies
# Source: http://www.iso.org/iso/support/faqs/faqs_widely_used_standards/widely_used_standards_other/currency_codes/currency_codes_list-1.htm
#
CURRENCY['AED'] = Currency(code='AED', prefix=u'د.إ', numeric='784', name='UAE Dirham', countries=['UNITED ARAB EMIRATES'])
CURRENCY['AFN'] = Currency(code='AFN', suffix=u'؋', numeric='971', name='Afghani', countries=['AFGHANISTAN'])
CURRENCY['ALL'] = Currency(code='ALL', prefix=u'L',    numeric='008', name='Lek', countries=['ALBANIA'])
CURRENCY['AMD'] = Currency(code='AMD', prefix=u'Դ', numeric='051', name='Armenian Dram', countries=['ARMENIA'])
CURRENCY['ANG'] = Currency(code='ANG', prefix=u'ƒ', numeric='532', name='Netherlands Antillian Guilder', countries=['NETHERLANDS ANTILLES'])
CURRENCY['AOA'] = Currency(code='AOA', prefix=u'Kz',   numeric='973', name='Kwanza', countries=['ANGOLA'])
CURRENCY['ARS'] = Currency(code='ARS', prefix=u'ARS$', numeric='032', name='Argentine Peso', countries=['ARGENTINA'])
CURRENCY['AUD'] = Currency(code='AUD', prefix=u'A$',   numeric='036', name='Australian Dollar', countries=['AUSTRALIA', 'CHRISTMAS ISLAND', 'COCOS (KEELING) ISLANDS', 'HEARD ISLAND AND MCDONALD ISLANDS', 'KIRIBATI', 'NAURU', 'NORFOLK ISLAND', 'TUVALU'])
CURRENCY['AWG'] = Currency(code='AWG', prefix=u'ƒ', numeric='533', name='Aruban Guilder', countries=['ARUBA'])
CURRENCY['AZN'] = Currency(code='AZN', numeric='944', name='Azerbaijanian Manat', countries=['AZERBAIJAN'])
CURRENCY['BAM'] = Currency(code='BAM', prefix=u'КМ', numeric='977', name='Convertible Marks', countries=['BOSNIA AND HERZEGOVINA'])
CURRENCY['BBD'] = Currency(code='BBD', prefix=u'Bds$', numeric='052', name='Barbados Dollar', countries=['BARBADOS'])
CURRENCY['BDT'] = Currency(code='BDT', prefix=u'৳', numeric='050', name='Taka', countries=['BANGLADESH'])
CURRENCY['BGN'] = Currency(code='BGN', prefix=u'лв', numeric='975', name='Bulgarian Lev', countries=['BULGARIA'])
CURRENCY['BHD'] = Currency(code='BHD', prefix=u'.د.ب', numeric='048', name='Bahraini Dinar', countries=['BAHRAIN'])
CURRENCY['BIF'] = Currency(code='BIF', prefix=u'FBu',  numeric='108', name='Burundi Franc', countries=['BURUNDI'])
CURRENCY['BMD'] = Currency(code='BMD', prefix=u'BD$',  numeric='060', name='Bermudian Dollar (customarily known as Bermuda Dollar)', countries=['BERMUDA'])
CURRENCY['BND'] = Currency(code='BND', prefix=u'B$',   numeric='096', name='Brunei Dollar', countries=['BRUNEI DARUSSALAM'])
CURRENCY['BRL'] = Currency(code='BRL', prefix=u'R$',   numeric='986', name='Brazilian Real', countries=['BRAZIL'])
CURRENCY['BSD'] = Currency(code='BSD', prefix=u'B$',   numeric='044', name='Bahamian Dollar', countries=['BAHAMAS'])
CURRENCY['BTN'] = Currency(code="BTN", prefix=u'Nu.')
CURRENCY['BWP'] = Currency(code='BWP', prefix=u'P',    numeric='072', name='Pula', countries=['BOTSWANA'])
CURRENCY['BYR'] = Currency(code='BYR', prefix=u'Br',   numeric='974', name='Belarussian Ruble', countries=['BELARUS'])
CURRENCY['BZD'] = Currency(code='BZD', prefix=u'BZ$',  numeric='084', name='Belize Dollar', countries=['BELIZE'])
CURRENCY['CAD'] = Currency(code='CAD', prefix=u'C$',   numeric='124', name='Canadian Dollar', countries=['CANADA'])
CURRENCY['CDF'] = Currency(code="CDF", prefix=u'C₣')
CURRENCY['CHF'] = Currency(code='CHF', prefix=u'Fr.',  numeric='756', name='Swiss Franc', countries=['LIECHTENSTEIN'])
CURRENCY['CLP'] = Currency(code="CLP", prefix=u'CLP$')
CURRENCY['CNY'] = Currency(code='CNY', prefix=u'¥',  numeric='156', name='Yuan Renminbi', countries=['CHINA'])
CURRENCY['COP'] = Currency(code="COP", prefix=u'COL$')
CURRENCY['CRC'] = Currency(code='CRC', prefix=u'₡',  numeric='188', name='Costa Rican Colon', countries=['COSTA RICA'])
CURRENCY['CUC'] = Currency(code="CUC", prefix=u'CUC$')
CURRENCY['CUP'] = Currency(code='CUP', prefix=u'$MN',  numeric='192', name='Cuban Peso', countries=['CUBA'])
CURRENCY['CVE'] = Currency(code='CVE', prefix=u'Esc',  numeric='132', name='Cape Verde Escudo', countries=['CAPE VERDE'])
CURRENCY['CZK'] = Currency(code='CZK', prefix=u'Kč',  numeric='203', name='Czech Koruna', countries=['CZECH REPUBLIC'])
CURRENCY['DJF'] = Currency(code='DJF', prefix=u'D₣',  numeric='262', name='Djibouti Franc', countries=['DJIBOUTI'])
CURRENCY['DKK'] = Currency(code='DKK', suffix=u' Dkr', numeric='208', name='Danish Krone', countries=['DENMARK', 'FAROE ISLANDS', 'GREENLAND'])
CURRENCY['DOP'] = Currency(code='DOP', prefix=u'RD$',  numeric='214', name='Dominican Peso', countries=['DOMINICAN REPUBLIC'])
CURRENCY['DZD'] = Currency(code='DZD', prefix=u'دج',  numeric='012', name='Algerian Dinar', countries=['ALGERIA'])
CURRENCY['EEK'] = Currency(code='EEK',                  numeric='233', name='Kroon', countries=['ESTONIA'])
CURRENCY['EGP'] = Currency(code='EGP', prefix=u'ج.م.',  numeric='818', name='Egyptian Pound', countries=['EGYPT'])
CURRENCY['ERN'] = Currency(code='ERN', prefix=u'Nfk',   numeric='232', name='Nakfa', countries=['ERITREA'])
CURRENCY['ETB'] = Currency(code='ETB', prefix=u'Br',    numeric='230', name='Ethiopian Birr', countries=['ETHIOPIA'])
CURRENCY['EUR'] = Currency(code='EUR', suffix=u' €',  numeric='978', name='Euro', countries=['ANDORRA', 'AUSTRIA', 'BELGIUM', 'FINLAND', 'FRANCE', 'FRENCH GUIANA', 'FRENCH SOUTHERN TERRITORIES', 'GERMANY', 'GREECE', 'GUADELOUPE', 'IRELAND', 'ITALY', 'LUXEMBOURG', 'MARTINIQUE', 'MAYOTTE', 'MONACO', 'MONTENEGRO', 'NETHERLANDS', 'PORTUGAL', 'R.UNION', 'SAINT PIERRE AND MIQUELON', 'SAN MARINO', 'SLOVENIA', 'SPAIN'])
CURRENCY['FJD'] = Currency(code='FJD', prefix=u'FJ$',  numeric='242', name='Fiji Dollar', countries=['FIJI'])
CURRENCY['FKP'] = Currency(code='FKP', prefix=u'FK£',  numeric='238', name='Falkland Islands Pound', countries=['FALKLAND ISLANDS (MALVINAS)'])
CURRENCY['GBP'] = Currency(code='GBP', prefix=u'£', prefix2=u'GB£',  numeric='826', name='Pound Sterling', countries=['UNITED KINGDOM'])
CURRENCY['GEL'] = Currency(code='GEL', prefix=u'ლ',  numeric='981', name='Lari', countries=['GEORGIA'])
CURRENCY['GHS'] = Currency(code='GHS', prefix=u'₵',  numeric='936', name='Ghana Cedi', countries=['GHANA'])
CURRENCY['GIP'] = Currency(code='GIP', prefix=u'GIP£', numeric='292', name='Gibraltar Pound', countries=['GIBRALTAR'])
CURRENCY['GMD'] = Currency(code='GMD', prefix=u'D',    numeric='270', name='Dalasi', countries=['GAMBIA'])
CURRENCY['GNF'] = Currency(code='GNF', prefix=u'G₣',  numeric='324', name='Guinea Franc', countries=['GUINEA'])
CURRENCY['GTQ'] = Currency(code='GTQ', prefix=u'Q',    numeric='320', name='Quetzal', countries=['GUATEMALA'])
CURRENCY['GYD'] = Currency(code='GYD', prefix=u'G$',   numeric='328', name='Guyana Dollar', countries=['GUYANA'])
CURRENCY['HKD'] = Currency(code='HKD', prefix=u'HK$', numeric='344', name='Hong Kong Dollar', countries=['HONG KONG'])
CURRENCY['HNL'] = Currency(code='HNL', prefix=u'L',   numeric='340', name='Lempira', countries=['HONDURAS'])
CURRENCY['HRK'] = Currency(code='HRK', suffix=u'kn',  numeric='191', name='Croatian Kuna', countries=['CROATIA'])
CURRENCY['HTG'] = Currency(code="HTG", prefix=u'G')
CURRENCY['HUF'] = Currency(code='HUF', prefix=u'Ft',  numeric='348', name='Forint', countries=['HUNGARY'])
CURRENCY['IDR'] = Currency(code='IDR', prefix=u'Rp',    numeric='360', name='Rupiah', countries=['INDONESIA'])
CURRENCY['ILS'] = Currency(code='ILS', prefix=u'₪',  numeric='376', name='New Israeli Sheqel', countries=['ISRAEL'])
CURRENCY['IMP'] = Currency(code="IMP", prefix=u'IM£')
CURRENCY['INR'] = Currency(code='INR', prefix=u'₹',  numeric='356', name='Indian Rupee', countries=['INDIA'])
CURRENCY['IQD'] = Currency(code='IQD', prefix=u'ع.د',  numeric='368', name='Iraqi Dinar', countries=['IRAQ'])
CURRENCY['IRR'] = Currency(code='IRR', prefix=u'ریال',  numeric='364', name='Iranian Rial', countries=['IRAN'])
CURRENCY['ISK'] = Currency(code='ISK', suffix=u' Íkr',  numeric='352', name='Iceland Krona', countries=['ICELAND'])
CURRENCY['JMD'] = Currency(code='JMD', prefix=u'J$',  numeric='388', name='Jamaican Dollar', countries=['JAMAICA'])
CURRENCY['JOD'] = Currency(code='JOD', prefix=u'JD',  numeric='400', name='Jordanian Dinar', countries=['JORDAN'])
CURRENCY['JPY'] = Currency(code='JPY', prefix=u'¥', numeric='392', name='Yen', countries=['JAPAN'])
CURRENCY['KES'] = Currency(code='KES', prefix=u'Ksh', numeric='404', name='Kenyan Shilling', countries=['KENYA'])
CURRENCY['KGS'] = Currency(code='KGS', prefix=u'лв',  numeric='417', name='Som', countries=['KYRGYZSTAN'])
CURRENCY['KHR'] = Currency(code='KHR', prefix=u'៛',  numeric='116', name='Riel', countries=['CAMBODIA'])
CURRENCY['KMF'] = Currency(code='KMF', prefix=u'C₣',  numeric='174', name='Comoro Franc', countries=['COMOROS'])
CURRENCY['KPW'] = Currency(code='KPW', prefix=u'₩',  numeric='408', name='North Korean Won', countries=['KOREA'])
CURRENCY['KRW'] = Currency(code='KRW', prefix=u'₩',  numeric='410', name='Won', countries=['KOREA'])
CURRENCY['KWD'] = Currency(code='KWD', prefix=u'د.ك',  numeric='414', name='Kuwaiti Dinar', countries=['KUWAIT'])
CURRENCY['KYD'] = Currency(code='KYD', prefix=u'CI$',   numeric='136', name='Cayman Islands Dollar', countries=['CAYMAN ISLANDS'])
CURRENCY['KZT'] = Currency(code='KZT',                  numeric='398', name='Tenge', countries=['KAZAKHSTAN'])
CURRENCY['LAK'] = Currency(code='LAK', prefix=u'₭', numeric='418', name='Kip', countries=['LAO PEOPLES DEMOCRATIC REPUBLIC'])
CURRENCY['LBP'] = Currency(code='LBP', prefix=u'LL', numeric='422', name='Lebanese Pound', countries=['LEBANON'])
CURRENCY['LKR'] = Currency(code='LKR', prefix=u'₨', numeric='144', name='Sri Lanka Rupee', countries=['SRI LANKA'])
CURRENCY['LRD'] = Currency(code='LRD', prefix=u'LD$', numeric='430', name='Liberian Dollar', countries=['LIBERIA'])
CURRENCY['LSL'] = Currency(code="LSL", prefix=u'M')
CURRENCY['LTL'] = Currency(code='LTL', prefix=u'Lt', numeric='440', name='Lithuanian Litas', countries=['LITHUANIA'])
CURRENCY['LVL'] = Currency(code='LVL', prefix=u'Ls', numeric='428', name='Latvian Lats', countries=['LATVIA'])
CURRENCY['LYD'] = Currency(code='LYD', prefix=u'ل.د', numeric='434', name='Libyan Dinar', countries=['LIBYAN ARAB JAMAHIRIYA'])
CURRENCY['MAD'] = Currency(code='MAD', prefix=u'د.م.', numeric='504', name='Moroccan Dirham', countries=['MOROCCO', 'WESTERN SAHARA'])
CURRENCY['MDL'] = Currency(code='MDL', numeric='498', name='Moldovan Leu', countries=['MOLDOVA'])
CURRENCY['MGA'] = Currency(code='MGA', prefix=u'Ar', numeric='969', name='Malagasy Ariary', countries=['MADAGASCAR'])
CURRENCY['MKD'] = Currency(code='MKD', prefix=u'ден', numeric='807', name='Denar', countries=['MACEDONIA'])
CURRENCY['MMK'] = Currency(code='MMK', prefix=u'K', numeric='104', name='Kyat', countries=['MYANMAR'])
CURRENCY['MNT'] = Currency(code='MNT', prefix=u'₮', numeric='496', name='Tugrik', countries=['MONGOLIA'])
CURRENCY['MOP'] = Currency(code='MOP', prefix=u'MOP$', numeric='446', name='Pataca', countries=['MACAO'])
CURRENCY['MRO'] = Currency(code='MRO', prefix=u'UM', numeric='478', name='Ouguiya', countries=['MAURITANIA'])
CURRENCY['MUR'] = Currency(code='MUR', prefix=u'₨', numeric='480', name='Mauritius Rupee', countries=['MAURITIUS'])
CURRENCY['MVR'] = Currency(code='MVR', prefix=u'Rf.', numeric='462', name='Rufiyaa', countries=['MALDIVES'])
CURRENCY['MWK'] = Currency(code='MWK', prefix=u'MK', numeric='454', name='Kwacha', countries=['MALAWI'])
CURRENCY['MXN'] = Currency(code="MXN", prefix=u'Mex$')
CURRENCY['MYR'] = Currency(code='MYR', prefix=u'RM',  numeric='458', name='Malaysian Ringgit', countries=['MALAYSIA'])
CURRENCY['MZN'] = Currency(code='MZN', prefix=u'MT', numeric='943', name='Metical', countries=['MOZAMBIQUE'])
CURRENCY['NAD'] = Currency(code="NAD", prefix=u'N$')
CURRENCY['NGN'] = Currency(code='NGN', prefix=u'₦', numeric='566', name='Naira', countries=['NIGERIA'])
CURRENCY['NIO'] = Currency(code='NIO', prefix=u'C$',  numeric='558', name='Cordoba Oro', countries=['NICARAGUA'])
CURRENCY['NOK'] = Currency(code='NOK', suffix=u' Nkr', numeric='578', name='Norwegian Krone', countries=['BOUVET ISLAND', 'NORWAY', 'SVALBARD AND JAN MAYEN'])
CURRENCY['NPR'] = Currency(code='NPR', prefix=u'₨', numeric='524', name='Nepalese Rupee', countries=['NEPAL'])
CURRENCY['NZD'] = Currency(code='NZD', prefix=u'NZ$',  numeric='554', name='New Zealand Dollar', countries=['COOK ISLANDS', 'NEW ZEALAND', 'NIUE', 'PITCAIRN', 'TOKELAU'])
CURRENCY['OMR'] = Currency(code='OMR', prefix=u'ر.ع.', numeric='512', name='Rial Omani', countries=['OMAN'])
CURRENCY['PEN'] = Currency(code='PEN', prefix=u'S/.',  numeric='604', name='Nuevo Sol', countries=['PERU'])
CURRENCY['PGK'] = Currency(code='PGK', prefix=u'K',    numeric='598', name='Kina', countries=['PAPUA NEW GUINEA'])
CURRENCY['PHP'] = Currency(code='PHP', prefix=u'₱', numeric='608', name='Philippine Peso', countries=['PHILIPPINES'])
CURRENCY['PKR'] = Currency(code='PKR', prefix=u'₨', numeric='586', name='Pakistan Rupee', countries=['PAKISTAN'])
CURRENCY['PLN'] = Currency(code='PLN', prefix=u'zł', numeric='985', name='Zloty', countries=['POLAND'])
CURRENCY['PYG'] = Currency(code='PYG', prefix=u'₲', numeric='600', name='Guarani', countries=['PARAGUAY'])
CURRENCY['QAR'] = Currency(code='QAR', prefix=u'ر.ق', numeric='634', name='Qatari Rial', countries=['QATAR'])
CURRENCY['RON'] = Currency(code='RON',                numeric='946', name='New Leu', countries=['ROMANIA'])
CURRENCY['RSD'] = Currency(code='RSD', prefix=u'дин', numeric='941', name='Serbian Dinar', countries=['SERBIA'])
CURRENCY['RUB'] = Currency(code='RUB', prefix=u'руб', numeric='643', name='Russian Ruble', countries=['RUSSIAN FEDERATION'])
CURRENCY['RWF'] = Currency(code='RWF', prefix=u'FRw',  numeric='646', name='Rwanda Franc', countries=['RWANDA'])
CURRENCY['SAR'] = Currency(code='SAR', prefix=u'ر.س', numeric='682', name='Saudi Riyal', countries=['SAUDI ARABIA'])
CURRENCY['SBD'] = Currency(code='SBD', prefix=u'SI$',  numeric='090', name='Solomon Islands Dollar', countries=['SOLOMON ISLANDS'])
CURRENCY['SCR'] = Currency(code='SCR', prefix=u'SRe',  numeric='690', name='Seychelles Rupee', countries=['SEYCHELLES'])
CURRENCY['SDG'] = Currency(code='SDG', prefix=u'S£', numeric='938', name='Sudanese Pound', countries=['SUDAN'])
CURRENCY['SEK'] = Currency(code='SEK', prefix=u' kr', suffix2=u' Skr', numeric='752', name='Swedish Krona', countries=['SWEDEN'])
CURRENCY['SGD'] = Currency(code='SGD', prefix=u'S$',   numeric='702', name='Singapore Dollar', countries=['SINGAPORE'])
CURRENCY['SHP'] = Currency(code='SHP', prefix=u'SH£', numeric='654', name='Saint Helena Pound', countries=['SAINT HELENA'])
CURRENCY['SKK'] = Currency(code='SKK', numeric='703', name='Slovak Koruna', countries=['SLOVAKIA'])
CURRENCY['SLL'] = Currency(code='SLL', prefix=u'Le',   numeric='694', name='Leone', countries=['SIERRA LEONE'])
CURRENCY['SOS'] = Currency(code='SOS', prefix=u'Sh.So.', numeric='706', name='Somali Shilling', countries=['SOMALIA'])
CURRENCY['SRD'] = Currency(code='SRD', prefix=u'SRD$', numeric='968', name='Surinam Dollar', countries=['SURINAME'])
CURRENCY['STD'] = Currency(code='STD', prefix=u'Db',   numeric='678', name='Dobra', countries=['SAO TOME AND PRINCIPE'])
CURRENCY['SYP'] = Currency(code='SYP', prefix=u'£S', numeric='760', name='Syrian Pound', countries=['SYRIAN ARAB REPUBLIC'])
CURRENCY['SZL'] = Currency(code='SZL', prefix=u'E',    numeric='748', name='Lilangeni', countries=['SWAZILAND'])
CURRENCY['THB'] = Currency(code='THB', prefix=u'฿', numeric='764', name='Baht', countries=['THAILAND'])
CURRENCY['TJS'] = Currency(code='TJS', numeric='972', name='Somoni', countries=['TAJIKISTAN'])
CURRENCY['TMM'] = Currency(code='TMM', numeric='795', name='Manat', countries=['TURKMENISTAN'])
CURRENCY['TND'] = Currency(code='TND', prefix=u'د.ت', numeric='788', name='Tunisian Dinar', countries=['TUNISIA'])
CURRENCY['TOP'] = Currency(code='TOP', prefix=u'TOP$', numeric='776', name='Paanga', countries=['TONGA'])
CURRENCY['TRY'] = Currency(code='TRY', prefix=u'TL', numeric='949', name='New Turkish Lira', countries=['TURKEY'])
CURRENCY['TTD'] = Currency(code='TTD', prefix=u'TT$', numeric='780', name='Trinidad and Tobago Dollar', countries=['TRINIDAD AND TOBAGO'])
CURRENCY['TVD'] = Currency(code="TVD", prefix=u'$T')
CURRENCY['TWD'] = Currency(code='TWD', prefix=u'NT$', numeric='901', name='New Taiwan Dollar', countries=['TAIWAN'])
CURRENCY['TZS'] = Currency(code='TZS', numeric='834', name='Tanzanian Shilling', countries=['TANZANIA'])
CURRENCY['UAH'] = Currency(code='UAH', prefix=u'₴', numeric='980', name='Hryvnia', countries=['UKRAINE'])
CURRENCY['UGX'] = Currency(code='UGX', prefix=u'USh', numeric='800', name='Uganda Shilling', countries=['UGANDA'])
CURRENCY['USD'] = Currency(code='USD', prefix=u'$', prefix2=u'US$', numeric='840', name='US Dollar', countries=['AMERICAN SAMOA', 'BRITISH INDIAN OCEAN TERRITORY', 'ECUADOR', 'GUAM', 'MARSHALL ISLANDS', 'MICRONESIA', 'NORTHERN MARIANA ISLANDS', 'PALAU', 'PUERTO RICO', 'TIMOR-LESTE', 'TURKS AND CAICOS ISLANDS', 'UNITED STATES MINOR OUTLYING ISLANDS', 'VIRGIN ISLANDS (BRITISH)', 'VIRGIN ISLANDS (U.S.)'])
CURRENCY['UYU'] = Currency(code="UYU", prefix=u'$U')
CURRENCY['UZS'] = Currency(code='UZS', numeric='860', name='Uzbekistan Sum', countries=['UZBEKISTAN'])
CURRENCY['VEF'] = Currency(code='VEF', prefix=u'Bs.', numeric='937', name='Bolivar Fuerte', countries=['VENEZUELA'])
CURRENCY['VND'] = Currency(code='VND', prefix=u'₫', numeric='704', name='Dong', countries=['VIET NAM'])
CURRENCY['VUV'] = Currency(code='VUV', prefix=u'VT', numeric='548', name='Vatu', countries=['VANUATU'])
CURRENCY['WST'] = Currency(code='WST', prefix=u'WS$', numeric='882', name='Tala', countries=['SAMOA'])
CURRENCY['XAG'] = Currency(code='XAG', prefix=u'FCFA', numeric='961', name='Silver', countries=[])
CURRENCY['XAU'] = Currency(code='XAU',                 numeric='959', name='Gold', countries=[])
CURRENCY['XBA'] = Currency(code='XBA',                 numeric='955', name='Bond Markets Units European Composite Unit (EURCO)', countries=[])
CURRENCY['XBB'] = Currency(code='XBB',                 numeric='956', name='European Monetary Unit (E.M.U.-6)', countries=[])
CURRENCY['XBC'] = Currency(code='XBC',                 numeric='957', name='European Unit of Account 9(E.U.A.-9)', countries=[])
CURRENCY['XBD'] = Currency(code='XBD',                 numeric='958', name='European Unit of Account 17(E.U.A.-17)', countries=[])
CURRENCY['XCD'] = Currency(code='XCD', prefix=u'EC$', numeric='951', name='East Caribbean Dollar', countries=['ANGUILLA', 'ANTIGUA AND BARBUDA', 'DOMINICA', 'GRENADA', 'MONTSERRAT', 'SAINT KITTS AND NEVIS', 'SAINT LUCIA', 'SAINT VINCENT AND THE GRENADINES'])
CURRENCY['XDR'] = Currency(code='XDR', prefix=u'SDR', numeric='960', name='SDR', countries=['INTERNATIONAL MONETARY FUND (I.M.F)'])
CURRENCY['XFO'] = Currency(code='XFO', numeric='Nil', name='Gold-Franc', countries=[])
CURRENCY['XFU'] = Currency(code='XFU', numeric='Nil', name='UIC-Franc', countries=[])
CURRENCY['XOF'] = Currency(code="XOF", prefix=u'CFA')
CURRENCY['XPD'] = Currency(code='XPD', numeric='964', name='Palladium', countries=[])
CURRENCY['XPF'] = Currency(code='XPF', numeric='953', name='CFP Franc', countries=['FRENCH POLYNESIA', 'NEW CALEDONIA', 'WALLIS AND FUTUNA'])
CURRENCY['XPT'] = Currency(code='XPT', numeric='962', name='Platinum', countries=[])
CURRENCY['XTS'] = Currency(code='XTS', numeric='963', name='Codes specifically reserved for testing purposes', countries=[])
CURRENCY['XXX'] = Currency(code='XXX', numeric='999', name='The codes assigned for transactions where no currency is involved are:', countries=[])
CURRENCY['YER'] = Currency(code='YER', numeric='886', name='Yemeni Rial', countries=['YEMEN'])
CURRENCY['ZAR'] = Currency(code='ZAR', prefix=u'R', numeric='710', name='Rand', countries=['SOUTH AFRICA'])
CURRENCY['ZMK'] = Currency(code='ZMK', prefix=u'ZK', numeric='894', name='Kwacha', countries=['ZAMBIA'])
CURRENCY['ZWD'] = Currency(code='ZWD', numeric='716', name='Zimbabwe Dollar', countries=['ZIMBABWE'])
CURRENCY['ZWL'] = Currency(code="ZWL", prefix=u'Z$')
